Readme / Links update
Zenoo/mui-theme-creator pull request #2
Opened 2022-04-22 21:56 UTC by ChrisCoastal

@Zenoo Here are the changes we discussed:

- updated the link in `Header.tsx` to point to this repo
- updated author / contact info throughout to reflect your maintenance of v5
- added a legacy section for MUI v4 users / acknowledgement to Brian Reynolds in the `README.md`
- removed commented out Gatsby instructions in `README.md`

Let me know of any changes. Thanks!

2022-04-22 22:03 UTC, Zenoo requested changes

2022-04-22 22:03 UTC, Zenoo commented on package.json
> +  "v5-author": "Zenoo <https://github.com/Zenoo>",
Those fields don't exist inside `package.json`.  
Instead, you could use the [`author` and `contributors` fields](https://classic.yarnpkg.com/lang/en/docs/package-json/#toc-maintainers).

2022-04-23 01:13 UTC, ChrisCoastal commented
Thanks for the link/resource! I'd not yet looked at a resource for the `package.json` properties (clearly). 😅 ✅

I amended with additional fields `keywords` and `homepage` also in `package.json`

2022-04-23 08:17 UTC, Zenoo approved these changes
Everything seems good, thanks for your contributions!

2022-04-23 08:17 UTC, merged

2022-04-23 17:10 UTC, ChrisCoastal commented
My pleasure. Thanks for all the work updating the tool for v5!